---
title: "Strings and factors"
author: "Shumei Liu"
date: "2024-10-15"
output: github_document
---

Load the necessary libraries

```{r}
library(rvest)

library(stringr) #use `str_detect` and `str_replace`

library(forcats) #use `fct_relevel`
```

## Let's do strings

```{r}
string_vec = c("my", "name", "is", "shumei")

str_detect(string_vec, "shumei")

str_replace(string_vec, "shumei", "Shumei")

str_replace(string_vec, "e", "E")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think") #beginning of the line
str_detect(string_vec, "i think$") #end of the line
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"pumpkin")
str_detect(string_vec,"Pumpkin")
str_detect(string_vec,"PUMPKIN")
str_detect(string_vec,"[Pp]umpkin")
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "[0-9]")
str_detect(string_vec, "[0-9][a-z]")
str_detect(string_vec, "[0-9][a-zA-Z]") #数字和字母连在一起
str_detect(string_vec, "^[0-9][a-zA-Z]")
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11")
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
```

## Factors

```{r}
sex_vec = factor(c("male", "male", "female", "female"))

sex_vec

as.numeric(sex_vec)
```

do some releveling

```{r}
sex_vec = fct_relevel(sex_vec, "male")

as.numeric(sex_vec)
```










